import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const crFont = localFont({
  src: '../public/font/cr_font.ttf',
  variable: '--font-cr',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${crFont.variable} antialiased font-cr bg-linear-to-b from-[#00aaff] to-[#002c81] min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}


